### ISSUE TITLE
Modify outputfile name by g++?

### ISSUE THREAD

**Issue by yyypasserby** [xuhdev/SingleCompile#62]
Is there any way to change the output file name like adding ```.out``` after the executable file in linux?

**Comment by xuhdev** [comment]
See [this line](https://github.com/xuhdev/SingleCompile/blob/master/autoload/SingleCompile/templates/cpp.vim#L81). Change `$(FILE_TITLE)$` to `$(FILE_TITLE)$.out`, and replace `g:SingleCompile_common_run_command` with `g:SingleCompile_common_run_command . 'out'`, then you should be good to go. If you don't want to touch the original file, you can copy them to your vimrc and change the compiler name, such as `g++-with-out`.

**Comment by yyypasserby** [comment]
Thanks, that works. And I think it should be ```g:SingleCompile_common_run_command . '.out'```.

**Comment by silentbluedrop** [comment]
@yyypasserby 
Hello, I have followed your instruction, but it doesn't work. What should I do?
here is the error(I edit p1.cpp, and set the output name as p1.out, but it seems like that it still use the name p1):
![image](https://user-images.githubusercontent.com/25808342/161720511-2f7a230e-1a03-42c0-9434-3d8c8924091a.png)
