### ISSUE TITLE
singlecompile with objective-c

### ISSUE THREAD

**Issue by SuperMarioBean** [xuhdev/SingleCompile#63]
I am new to use singlecompile. is there a simple way to link objc framework such as Foundation.framework to the source file? for example, I write simple.m

    #import <Foundation/Foundation.h>

    int main(int argc, char *argv[]) {
	    @autoreleasepool {
		    NSLog(@"hello world");
	    }
    }

and in vim I run :SCCompile , and it occurs to these:

    Undefined symbols for architecture x86_64:
      "_NSLog", referenced from:
          _main in sample-c42ea1.o
      "___CFConstantStringClassReference", referenced from:
          CFString in sample-c42ea1.o
      "_objc_autoreleasePoolPop", referenced from:
          _main in sample-c42ea1.o
      "_objc_autoreleasePoolPush", referenced from:
          _main in sample-c42ea1.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I think it is the Foundation.framework is not link in link time, so I wanna know how to solve it with SingleCompile

**Comment by xuhdev** [comment]
You can look into `:SCCompileAF`

**Comment by SuperMarioBean** [comment]
oh, thanks!!!
