### ISSUE TITLE
ccache Support?

### ISSUE THREAD

**Issue by htfy96** [xuhdev/SingleCompile#65]
I want to use `ccache gcc xxx.cpp` to compile my code, but still now I can't find any way to support ccache. Is there any solution to this problem?

**Comment by xuhdev** [comment]
You can add a new template. See `:h SingleCompile-compiler-template`. A list of examples can be seen [here](https://github.com/xuhdev/SingleCompile/blob/master/autoload/SingleCompile/templates/c.vim)
