### ISSUE TITLE
How to add flag '-lm'?

### ISSUE THREAD

**Issue by szsdk** [xuhdev/SingleCompile#70]
When using flag '-lm', it should be
`gcc a.c -lm -o a`
But if I use
SCCompileAF -lm
the running command is
`gcc -lm a.c -o a`
It is wrong.

**Comment by xuhdev** [comment]
`-lm` should automatically be added if `#include <math.h>` is found:

https://github.com/xuhdev/SingleCompile/blob/master/autoload/SingleCompile.vim#L331

Let me know if you have more questions.

**Comment by xuhdev** [comment]
BTW, please also pull the latest version as I've fixed the location of `-lm`.

**Comment by szsdk** [comment]
It's worked. Thanks.
