### ISSUE TITLE
How do I compile with arguments with this plugin

### ISSUE THREAD

**Issue by jfeve** [xuhdev/SingleCompile#75]
Hi, 
I'm using single compile for now 2 days. I'm a C programer, and so I'm programing with mains using arguments after the name of the exec (example : ./a.out "Bonjour"). But I don't know how to compile with arguments with single compile. Maybe I missed something. Can someone tell me how to do it ?

**Comment by xuhdev** [comment]
Use `:SCCompileAF` and `:SCCompileRunAF`.
