### ISSUE TITLE
Output of SCChooseCompiler does not show gcc-8 though it is in PATH

### ISSUE THREAD

**Issue by nvijayap** [xuhdev/SingleCompile#76]
Hello,

On Mac, how can I add gcc-8 to the list of compilers that SingleCompile can recognize as a valid compiler? Output of SCChooseCompiler does not show gcc-8 though it is in PATH.

Thanks
Naga Vijayapuram

**Comment by nvijayap** [comment]
I have overcome by modifying c.vim ...

```
79,81c79,81
<     call SingleCompile#SetCompilerTemplate('c', 'gcc', 'GNU C Compiler',
<                 \'gcc', '-g -o $(FILE_TITLE)$', g:SingleCompile_common_run_command)
<     call SingleCompile#SetCompilerTemplateByDict('c', 'gcc', {
---
>     call SingleCompile#SetCompilerTemplate('c', 'gcc-8', 'GNU C Compiler',
>                 \'gcc-8', '-ansi -Wall -Werror -o $(FILE_TITLE)$', g:SingleCompile_common_run_command)
>     call SingleCompile#SetCompilerTemplateByDict('c', 'gcc-8', {
```

**Comment by xuhdev** [comment]
Actually you shouldn't need to modify `c.vim` -- it will be overridden once you update the plugin. Instead, check out `:h SingleCompile-add-your-compiler`.
