### ISSUE TITLE
Command-Line Args

### ISSUE THREAD

**Issue by nvijayap** [xuhdev/SingleCompile#77]
Hello,

How to pass command-line args?  I am trying to compile and run this very simple program from within Vim and see the complete output ...

```
#include <stdio.h>

int main(int argc, char *argv[])
{
  int i =0;

  for (; i<argc; i++) {
    printf("Arg %d is %s\n", i, argv[i]);
  }

  return 0;
}
```

Thanks
Naga Vijayapuram

**Comment by xuhdev** [comment]
`:h :SCCompileAF`
