### ISSUE TITLE
singlecompile: language template for "javascript.jsx" is not defined on your system.

### ISSUE THREAD

**Issue by hjeont** [xuhdev/SingleCompile#80]
Whenever I type in :SCCompileRun<CR> on any *.js file, There is this 

> singlecompile: language template for "javascript.jsx" is not defined on your system.

error message. I can find no known issue for this. Can anyone help?

**Comment by hjeont** [comment]
My system is mac OSX Mojave, and I already have nodejs on it.

**Comment by hjeont** [comment]
It says `filetype=javascript.jsx`.

**Comment by xuhdev** [comment]
The file type is changed to something non-standard. Are you using [vim-jsx](https://github.com/mxw/vim-jsx), I guess? If this is the case, I think you should consult them to stop altering filetypes as many other plugins would rely on the very value of `filetype`. It should not be our responsibility to take care of this alteration unless it can be shown to be reasonable and necessary.

**Comment by hjeont** [comment]
I'm using neovim 0.3.4, and solved this by adding `let g:jsx_ext_required = 1` to my vimrc. Thank you!
